[cache]
type = "file"
basepath = "cache"

[[providers]]
name = "osm2pgsql"
type = "postgis"
host = "/var/run/postgresql" # Default for Debian-based distributions
port = 5432                     # postgis database port
database = "gis"        # postgis database name
user = "pnorman"
password = ""

  [[providers.layers]]
  name = "ne_water"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way
    FROM (
    SELECT
        way
      FROM ne_ocean
      WHERE way && !BBOX!
    UNION ALL
    SELECT
        way
      FROM ne_lake
      WHERE way && !BBOX!
    ) _
  """

  [[providers.layers]]
  name = "lz_water"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way
    FROM (
      SELECT
          way
        FROM simplified_ocean_polygons
        WHERE way && !BBOX!
      UNION ALL
      SELECT
          way
        FROM planet_osm_polygon
        WHERE way && !BBOX!
          AND (waterway = 'riverbank'
            OR landuse = 'reservoir'
            OR "natural" = 'water')
          AND way_area > pixel_size(9)*4 -- working around tegola #343
    ) _
  """

  [[providers.layers]]
  name = "water"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way
    FROM (
      SELECT
          way
        FROM ocean_polygons
        WHERE way && !BBOX!
      UNION ALL
      SELECT
          way
        FROM planet_osm_polygon
        WHERE way && !BBOX!
          AND (waterway = 'riverbank'
            OR landuse = 'reservoir'
            OR "natural" = 'water')
          AND way_area > pixel_size(12)*4 -- working around tegola #343
    ) _
  """

  [[providers.layers]]
  name = "water_names"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way
    FROM (
      SELECT
          ST_PointOnSurface(way) AS way,
          name
        FROM planet_osm_polygon
        WHERE way && !BBOX!
          AND name IS NOT NULL
          AND (waterway = 'riverbank'
            OR landuse = 'reservoir'
            OR "natural" = 'water')
          AND way_area > pixel_size(12)*16 -- working around tegola #343
    ) _
    WHERE way && !BBOX!
  """

  [[providers.layers]]
  name = "transport_z6"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way,
      name
    FROM (
      SELECT
          way,
          name,
          ref,
          highway AS class -- strip link
        FROM planet_osm_roads
        WHERE way && !BBOX!
          AND highway IN ('motorway')
    ) _
  """

  [[providers.layers]]
  name = "transport_z7"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way,
      name
    FROM (
      SELECT
          way,
          name,
          ref,
          highway AS class -- strip link
        FROM planet_osm_roads
        WHERE way && !BBOX!
          AND highway IN ('motorway', 'trunk')
    ) _
  """

  [[providers.layers]]
  name = "transport_z8"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way,
      name
    FROM (
      SELECT
          way,
          name,
          ref,
          highway AS class -- strip link
        FROM planet_osm_roads
        WHERE way && !BBOX!
          AND highway IN ('motorway', 'trunk', 'primary')
    ) _
  """

  [[providers.layers]]
  name = "transport_z9"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way,
      name
    FROM (
      SELECT
          way,
          name,
          ref,
          highway AS class -- strip link
        FROM planet_osm_roads
        WHERE way && !BBOX!
          AND highway IN ('motorway', 'trunk', 'primary', 'secondary')
    ) _
  """

  [[providers.layers]]
  name = "transport_z10"
  id_fieldname = "osm_id"
  geometry_fieldname = "way"
  sql = """
  SELECT
      row_number() OVER () AS osm_id,
      ST_AsBinary(way) AS way,
      name
    FROM (
      SELECT
          way,
          name,
          ref,
          highway AS class -- strip link
        FROM planet_osm_line
        WHERE way && !BBOX!
          AND highway IN ('motorway', 'motorway_link', 'trunk', 'trunk_link', 'primary', 'primary_link',
                          'secondary', 'secondary_link', 'tertiary', 'tertiary_link')
    ) _
  """

[[maps]]
name = "bolder"

[[maps.layers]]
name = "water"
provider_layer = "osm2pgsql.ne_water"
min_zoom = 0
max_zoom = 5

[[maps.layers]]
name = "water"
provider_layer = "osm2pgsql.lz_water"
min_zoom = 6
max_zoom = 9

[[maps.layers]]
name = "water"
provider_layer = "osm2pgsql.water"
min_zoom = 10

[[maps.layers]]
name = "water_names"
provider_layer = "osm2pgsql.water_names"
min_zoom = 10

[[maps.layers]]
name = "transport"
provider_layer = "osm2pgsql.transport_z6"
min_zoom = 6
max_zoom = 6

[[maps.layers]]
name = "transport"
provider_layer = "osm2pgsql.transport_z7"
min_zoom = 7
max_zoom = 7

[[maps.layers]]
name = "transport"
provider_layer = "osm2pgsql.transport_z8"
min_zoom = 8
max_zoom = 8

[[maps.layers]]
name = "transport"
provider_layer = "osm2pgsql.transport_z9"
min_zoom = 9
max_zoom = 9

[[maps.layers]]
name = "transport"
provider_layer = "osm2pgsql.transport_z10"
min_zoom = 10
max_zoom = 10
