postgresql:
  dbnames: [gis]
queries:
  config: layers.yaml
  template-path: queries
  reload-templates: true

formats: [json, topojson, mvt]
buffer: {}

server:
  # The host and port need to match what the Tangram scene file specifies
  host: localhost
  port: 8080
  debug: true
  reload: true
  threaded: true

http:
  # whether to include cors headers on responses
  cors: true
  # client cache time in seconds ("Cache-Control: max-age" header)
  max-age: 300

# optional for health checks. This can be useful for monitoring to
# verify that the service is still running and can connect to the
# database.
health:
  # request path to listen for health checks
  url: /_health

# to support requesting tiles for different metatile sizes
# these should get prefixed to the beginning of the url path
path_tile_size:
  # NOTE: the keys should be strings
  "256": 1
  "512": 2

# requests for zoom levels higher than this will 404
max_interesting_zoom: 15
